[tool.poetry]
name = "ghostiss"
version = "0.0.1"
description = "model-oriented operation system"
authors = ["thirdgerb <thirdgerb@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <3.13"
pydantic = "^2.7.0"
pytest = "^8.1.1"
openai = "^1.19.0"
pyyaml = "^6.0.1"
rich = "^13.7.1"
httpx-socks = "^0.9.1"
restrictedpython = "^7.1"
datasets = "^2.20.0"
anthropic = "^0.31.2"
pillow = "^10.4.0"
sympy = "^1.13.1"
tree-sitter = "0.21.3"
tree-sitter-languages = "^1.10.2"
mem0ai = "^0.0.20"
networkx = "^3.3"
grep-ast = "^0.3.3"
litellm = "^1.43.18"
hide-py = "^0.3.0"

[tool.poetry.scripts]
llm_test = "ghostiss.scripts.llm_test:main"
moss_test = "ghostiss.scripts.moss_test:main"
moss_run = "ghostiss.scripts.moss_run:main"
aifunc_test = "ghostiss.scripts.aifunc_test:main"
swe_test = "ghostiss.scripts.swe_test:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
