[tool.poetry]
name = "ghostiss"
version = "0.0.1"
description = "model-oriented operation system"
authors = ["thirdgerb <thirdgerb@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.0"
pytest = "^8.1.1"
openai = "^1.19.0"
pyyaml = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
