[tool.poetry]
name = "ghostos"
version = "0.0.1"
description = "An agent framework offering agents and meta-agents a Python code interface to operate everything."
authors = ["zhuming <thirdgerb@gmail.com>", "Nile Zhou <nilezhou123@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.0"
pytest = "^8.1.1"
openai = "^1.19.0"
pyyaml = "^6.0.1"
rich = "^13.7.1"
httpx-socks = "^0.9.1"
datasets = "^2.20.0"
anthropic = "^0.31.2"
sympy = "^1.13.1"
tree-sitter = "0.21.3"
tree-sitter-languages = "^1.10.2"
networkx = "^3.3"
grep-ast = "^0.3.3"
litellm = "^1.43.18"
hide-py = "^0.3.0"
prompt-toolkit = "^3.0.47"
arxiv = "^2.1.3"
llama-index-core = "^0.11.9"
llama-index-llms-openai = "^0.2.7"
streamlit = "^1.39.0"
pydantic-settings = "^2.5.2"
streamlit-antd-components = "^0.3.2"
streamlit-react-jsonschema = "^0.1.3"

[tool.poetry.scripts]
init = "ghostos.scripts.init:main"
demo = "ghostos.demo.scripts.demo:main"
llm_test = "ghostos.demo.scripts.llm_test:main"
clear_runtime = "ghostos.demo.scripts.clear_runtime:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
