# logging_config.yml

version: 1

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s: %(message)s"
  context_formatter:
    format: "%(asctime)s - %(name)s - %(levelname)s: %(message)s - %(trace)s"

handlers:
  debug_file:
    class: logging.FileHandler
    filename: debug.log
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout

loggers:
  debug:
    handlers: [ debug_file ]
    level: DEBUG
  console:
    handlers: [ console ]
    level: DEBUG
